version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Build static site
          command: |
            curl -O https://github.com/s3tools/s3cmd/releases/download/v2.0.2/s3cmd-2.0.2.tar.gz
            tar -xvzf s3cmd-2.0.2.tar.gz
            s3cmd get https://justanotherdot.nyc3.digitaloceanspaces.com/build-site
            build-site
