version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Build static site image
          command: |
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
            docker build -t justanotherdot/blog:$CIRCLE_BRANCH .
