version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build static site image
          command: |
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
            docker build -t --build-arg AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY justanotherdot/blog:$CIRCLE_SHA1 .
