steps:
  - label: "Rust: nightly"
    command:
      - "cargo +nightly build"
      - "cargo +nightly test"
    plugins:
      - docker-compose#v3.0.3:
          run: rust_nightly_ci
    retry:
      automatic:
        - exit_status: "*"
          limit: 3
