[package]
name = "site-gen"
version = "0.1.0"
authors = ["Ryan James Spencer <spencer.ryanjames@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.98"
ramhorns = "0.5.0"
pulldown-cmark = "0.5.3"
